application: yama-stage
version: 3
runtime: go
api_version: go1

handlers:

  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  - url: /(.*\.(css|gif|png|jpgjs|html))
    static_files: static/\2/\1
    upload: static/(.*\.(css|gif|png|jpg|js|html))

  - url: /admin/.*
    script: _go_app
    login: required

  - url: /.*
    script: _go_app
    #login: required

